In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
cola = yf.Ticker('KO')
cola_balance = cola.balance_sheet
cola_income = cola.income_stmt
cola_cf = cola.cash_flow

In [3]:
pepsi = yf.Ticker('PEP')
pepsi_balance = pepsi.balance_sheet
pepsi_income = pepsi.income_stmt
pepsi_cf = pepsi.cash_flow

In [4]:
pepsi_income.head(100)

2022-12-31  \
Tax Effect Of Unusual Items                            31000000.0   
Tax Rate For Calcs                                            0.2   
Normalized EBITDA                                   14769000000.0   
Total Unusual Items                                   155000000.0   
Total Unusual Items Excluding Goodwill                155000000.0   
Net Income From Continuing Operation Net Minori...   8910000000.0   
Reconciled Depreciation                              3280000000.0   
Reconciled Cost Of Revenue                          40576000000.0   
EBITDA                                              14924000000.0   
EBIT                                                11644000000.0   
Net Interest Income                                  -939000000.0   
Interest Expense                                      939000000.0   
Interest Income                                               NaN   
Normalized Income                                    8786000000.0   
Net Income From Continuing And Discontinued Ope...   8910000000.0   
Total Expenses                                      75035000000.0   
Total Operating Income As Reported                  11512000000.0   
Diluted Average Shares                               1387000000.0   
Basic Average Shares                                 1380000000.0   
Diluted EPS                                                  6.42   
Basic EPS                                                    6.45   
Diluted NI Availto Com Stockholders                  8910000000.0   
Average Dilution Earnings                                     NaN   
Net Income Common Stockholders                       8910000000.0   
Otherunder Preferred Stock Dividend                           NaN   
Net Income                                           8910000000.0   
Minority Interests                                    -68000000.0   
Net Income Including Noncontrolling Interests        8978000000.0   
Net Income Continuous Operations                     8978000000.0   
Tax Provision                                        1727000000.0   
Pretax Income                                       10705000000.0   
Other Income Expense                                  287000000.0   
Other Non Operating Income Expenses                   132000000.0   
Special Income Charges                                155000000.0   
Impairment Of Capital Assets                         3166000000.0   
Restructuring And Mergern Acquisition               -3321000000.0   
Net Non Operating Interest Income Expense            -939000000.0   
Interest Expense Non Operating                        939000000.0   
Interest Income Non Operating                                 NaN   
Operating Income                                    11357000000.0   
Operating Expense                                   34459000000.0   
Selling General And Administration                  34459000000.0   
Gross Profit                                        45816000000.0   
Cost Of Revenue                                     40576000000.0   
Total Revenue                                       86392000000.0   
Operating Revenue                                   86392000000.0   

                                                       2021-12-31  \
Tax Effect Of Unusual Items                                   0.0   
Tax Rate For Calcs                                          0.218   
Normalized EBITDA                                   14899000000.0   
Total Unusual Items                                           NaN   
Total Unusual Items Excluding Goodwill                        NaN   
Net Income From Continuing Operation Net Minori...   7618000000.0   
Reconciled Depreciation                              3215000000.0   
Reconciled Cost Of Revenue                          37075000000.0   
EBITDA                                              14899000000.0   
EBIT                                                11684000000.0   
Net Interest Income                                 

In [5]:
#get for quarterly report
cola_balance_quarter=yf.Ticker('KO').quarterly_balance_sheet
cola_income_quarter=yf.Ticker('KO').quarterly_income_stmt
cola_cf_quarter=yf.Ticker('KO').quarterly_cashflow

pepsi_balance_quarter=yf.Ticker('PEP').quarterly_balance_sheet
pepsi_income_quarter=yf.Ticker('PEP').quarterly_income_stmt
pepsi_cf_quarter=yf.Ticker('PEP').quarterly_cashflow


In [6]:
cola_income_quarter.head(30)

2023-09-30  \
Tax Effect Of Unusual Items                                  0.0   
Tax Rate For Calcs                                         0.128   
Normalized EBITDA                                   4195000000.0   
Total Unusual Items                                 -428000000.0   
Total Unusual Items Excluding Goodwill              -428000000.0   
Net Income From Continuing Operation Net Minori...  3087000000.0   
Reconciled Depreciation                              290000000.0   
Reconciled Cost Of Revenue                          4657000000.0   
EBITDA                                              4195000000.0   
EBIT                                                3905000000.0   
Net Interest Income                                 -120000000.0   
Interest Expense                                     368000000.0   
Interest Income                                      248000000.0   
Normalized Income                                   3087000000.0   
Net Income From Continuing And Discontinued Ope...  3087000000.0   
Total Expenses                                      8683000000.0   
Total Operating Income As Reported                  3270000000.0   
Diluted Average Shares                              4339000000.0   
Basic Average Shares                                4324000000.0   
Diluted EPS                                                 0.71   
Basic EPS                                                   0.71   
Diluted NI Availto Com Stockholders                 3087000000.0   
Net Income Common Stockholders                      3087000000.0   
Net Income                                          3087000000.0   
Minority Interests                                     4000000.0   
Net Income Including Noncontrolling Interests       3083000000.0   
Net Income Continuous Operations                    3083000000.0   
Tax Provision                                        454000000.0   
Pretax Income                                       3537000000.0   
Other Income Expense                                 387000000.0   

                                                      2023-06-30  \
Tax Effect Of Unusual Items                                  0.0   
Tax Rate For Calcs                                         0.125   
Normalized EBITDA                                   3535000000.0   
Total Unusual Items                                -1314000000.0   
Total Unusual Items Excluding Goodwill             -1314000000.0   
Net Income From Continuing Operation Net Minori...  2547000000.0   
Reconciled Depreciation                              281000000.0   
Reconciled Cost Of Revenue                          4912000000.0   
EBITDA                                              3535000000.0   
EBIT                                                3254000000.0   
Net Interest Income                                 -150000000.0   
Interest Expense                                     374000000.0   
Interest Income                                      224000000.0   
Normalized Income                                   2547000000.0   
Net Income From Continuing And Discontinued Ope...  2547000000.0   
Total Expenses                                      9571000000.0   
Total Operating Income As Reported                  2401000000.0   
Diluted Average Shares                              4341000000.0   
Basic Average Shares                                4325000000.0   
Diluted EPS                                                 0.59   
Basic EPS                                                   0.59   
Diluted NI Availto Com Stockholders                 2547000000.0   
Net Income Common Stockholders                      2547000000.0   
Net Income                                          2547000000.0   
Minority Interests                                    26000000.0   
Net Income Including Noncontrolling Interests       2521000000.0   
Net Income Continuous Operations                    2521000000.0   
Tax Provision                            

#The observation around financial metrics will be concentrated on
### business volume 
#### -total revenue
#### -revenue growth
#### -revenue structure/ per geo or per business
#### -non-financial market stats
### profitability
#### -gross margin/ebit
#### -marketing investment
#### -cost/expense analysis
### solvency and liquidity
#### -leverage ratio
#### -ebit/interest ratio
#### -liquidity ratios
### working capital efficiency
#### -DSO
#### -ITO
#### -DPO
#### -CCC
### capital market performance
#### -MARKET CAP and price
#### -EPS/PE ratio/PB ratio

In [7]:
# total sales
pepsi_income_quarter.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, Tax Effect Of Unusual Items to Operating Revenue
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   2023-09-30 00:00:00  43 non-null     object
 1   2023-06-30 00:00:00  43 non-null     object
 2   2023-03-31 00:00:00  43 non-null     object
 3   2022-12-31 00:00:00  42 non-null     object
 4   2022-09-30 00:00:00  43 non-null     object
dtypes: object(5)
memory usage: 2.0+ KB


In [8]:
cola_balance_quarter.head(200)

2023-09-30  \
Treasury Shares Number                             2716000000.0   
Ordinary Shares Number                             4324000000.0   
Share Issued                                       7040000000.0   
Net Debt                                          28288000000.0   
Total Debt                                        40171000000.0   
...                                                         ...   
Allowance For Doubtful Accounts Receivable         -504000000.0   
Gross Accounts Receivable                          3999000000.0   
Cash Cash Equivalents And Short Term Investments  15435000000.0   
Other Short Term Investments                       3552000000.0   
Cash And Cash Equivalents                         11883000000.0   

                                                     2023-06-30  \
Treasury Shares Number                             2716000000.0   
Ordinary Shares Number                             4324000000.0   
Share Issued                                       7040000000.0   
Net Debt                                          29061000000.0   
Total Debt                                        41625000000.0   
...                                                         ...   
Allowance For Doubtful Accounts Receivable         -510000000.0   
Gross Accounts Receivable                          4480000000.0   
Cash Cash Equivalents And Short Term Investments  15694000000.0   
Other Short Term Investments                       3130000000.0   
Cash And Cash Equivalents                         12564000000.0   

                                                     2023-03-31  \
Treasury Shares Number                             2715000000.0   
Ordinary Shares Number                             4325000000.0   
Share Issued                                       7040000000.0   
Net Debt                                          30396000000.0   
Total Debt                                        42400000000.0   
...                                                         ...   
Allowance For Doubtful Accounts Receivable         -512000000.0   
Gross Accounts Receivable                          5111000000.0   
Cash Cash Equivalents And Short Term Investments  14295000000.0   
Other Short Term Investments                       2291000000.0   
Cash And Cash Equivalents                         12004000000.0   

                                                     2022-12-31     2022-09-30  
Treasury Shares Number                             2712000000.0   2716000000.0  
Ordinary Shares Number                             4328000000.0   4324000000.0  
Share Issued                                       7040000000.0   7040000000.0  
Net Debt                                          29630000000.0  29460000000.0  
Total Debt                                        39149000000.0  39587000000.0  
...                                                         ...            ...  
Allowance For Doubtful Accounts Receivable         -516000000.0   -517000000.0  
Gross Accounts Receivable                          4003000000.0   4511000000.0  
Cash Cash Equivalents And Short Term Investments  11631000000.0  13220000000.0  
Other Short Term Investments                       2112000000.0   3093000000.0  
Cash And Cash Equivalents                          9519000000.0  10127000000.0  

[74 rows x 5 columns]

In [9]:
#1.transform 12 tables
#1.1 add company labels
# coke 10k
cola_balance.insert(0, 'Company Name', 'coca')
cola_income.insert(0, 'Company Name', 'coca')
cola_cf.insert(0, 'Company Name', 'coca')

# pepsi 10k
pepsi_balance.insert(0, 'Company Name', 'pepsi')
pepsi_income.insert(0, 'Company Name', 'pepsi')
pepsi_cf.insert(0, 'Company Name', 'pepsi')


In [10]:
pepsi_balance


Company Name  \
Treasury Shares Number                                  pepsi   
Ordinary Shares Number                                  pepsi   
Share Issued                                            pepsi   
Net Debt                                                pepsi   
Total Debt                                              pepsi   
...                                                       ...   
Other Receivables                                       pepsi   
Accounts Receivable                                     pepsi   
Cash Cash Equivalents And Short Term Investments        pepsi   
Other Short Term Investments                            pepsi   
Cash And Cash Equivalents                               pepsi   

                                                 2022-12-31 00:00:00  \
Treasury Shares Number                                   490000000.0   
Ordinary Shares Number                                  1377000000.0   
Share Issued                                            1867000000.0   
Net Debt                                               34117000000.0   
Total Debt                                             39071000000.0   
...                                                              ...   
Other Receivables                                       2121000000.0   
Accounts Receivable                                    10163000000.0   
Cash Cash Equivalents And Short Term Investments        5348000000.0   
Other Short Term Investments                             394000000.0   
Cash And Cash Equivalents                               4954000000.0   

                                                 2021-12-31 00:00:00  \
Treasury Shares Number                                   484000000.0   
Ordinary Shares Number                                  1383000000.0   
Share Issued                                            1867000000.0   
Net Debt                                               34738000000.0   
Total Debt                                             40334000000.0   
...                                                              ...   
Other Receivables                                       1655000000.0   
Accounts Receivable                                     8680000000.0   
Cash Cash Equivalents And Short Term Investments        5988000000.0   
Other Short Term Investments                             392000000.0   
Cash And Cash Equivalents                               5596000000.0   

                                                 2020-12-31 00:00:00  \
Treasury Shares Number                                   487000000.0   
Ordinary Shares Number                                  1380000000.0   
Share Issued                                            1867000000.0   
Net Debt                                               35965000000.0   
Total Debt                                             44150000000.0   
...                                                              ...   
Other Receivables                                       1713000000.0   
Accounts Receivable                                     8404000000.0   
Cash Cash Equivalents And Short Term Investments        9551000000.0   
Other Short Term Investments                            1366000000.0   
Cash And Cash Equivalents                               8185000000.0   

                                                 2019-12-31 00:00:00  
Treasury Shares Number                                   476000000.0  
Ordinary Shares Number                                  1391000000.0  
Share Issued                                            1867000000.0  
Net Debt                                               26559000000.0  
Total Debt                                             32068000000.0  
...                                                              ...  
Other Receivables                                       1480000000.0  
Accounts Receivable                                     7822000000.0  
Cash Cash Equivalents And Short Te

In [11]:
pepsi_balance.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in pepsi_balance.columns]
pepsi_income.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in pepsi_income.columns]
pepsi_cf.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in pepsi_cf.columns]

In [12]:
cola_balance.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in cola_balance.columns]
cola_income.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in cola_income.columns]
cola_cf.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in cola_cf.columns]


In [13]:
#labelize data source
#cola 10k
cola_balance.insert(0, 'Data Source', 'bs')
cola_income.insert(0, 'Data Source', 'is')
cola_cf.insert(0, 'Data Source', 'cf')

# pepsi 10k
pepsi_balance.insert(0, 'Data Source', 'bs')
pepsi_income.insert(0, 'Data Source', 'is')
pepsi_cf.insert(0, 'Data Source', 'cf')

In [14]:
# index to indicators
# cola
cola_balance = cola_balance.reset_index().rename(columns={'index': 'Financial Indicators'})
cola_income = cola_income.reset_index().rename(columns={'index': 'Financial Indicators'})
cola_cf = cola_cf.reset_index().rename(columns={'index': 'Financial Indicators'})

# pepsi
pepsi_balance = pepsi_balance.reset_index().rename(columns={'index': 'Financial Indicators'})
pepsi_income = pepsi_income.reset_index().rename(columns={'index': 'Financial Indicators'})
pepsi_cf = pepsi_cf.reset_index().rename(columns={'index': 'Financial Indicators'})


In [15]:
pepsi_balance

Financial Indicators Data Source Company Name  \
0                             Treasury Shares Number          bs        pepsi   
1                             Ordinary Shares Number          bs        pepsi   
2                                       Share Issued          bs        pepsi   
3                                           Net Debt          bs        pepsi   
4                                         Total Debt          bs        pepsi   
..                                               ...         ...          ...   
77                                 Other Receivables          bs        pepsi   
78                               Accounts Receivable          bs        pepsi   
79  Cash Cash Equivalents And Short Term Investments          bs        pepsi   
80                      Other Short Term Investments          bs        pepsi   
81                         Cash And Cash Equivalents          bs        pepsi   

       2022-12-31     2021-12-31     2020-12-31     2019-12-31  
0     490000000.0    484000000.0    487000000.0    476000000.0  
1    1377000000.0   1383000000.0   1380000000.0   1391000000.0  
2    1867000000.0   1867000000.0   1867000000.0   1867000000.0  
3   34117000000.0  34738000000.0  35965000000.0  26559000000.0  
4   39071000000.0  40334000000.0  44150000000.0  32068000000.0  
..            ...            ...            ...            ...  
77   2121000000.0   1655000000.0   1713000000.0   1480000000.0  
78  10163000000.0   8680000000.0   8404000000.0   7822000000.0  
79   5348000000.0   5988000000.0   9551000000.0   5738000000.0  
80    394000000.0    392000000.0   1366000000.0    229000000.0  
81   4954000000.0   5596000000.0   8185000000.0   5509000000.0  

[82 rows x 7 columns]

In [16]:
form10k_inone=pd.concat([cola_balance,cola_income,cola_cf,pepsi_balance,pepsi_income,pepsi_cf])

In [17]:
form10k_inone

Financial Indicators Data Source Company Name  \
0                  Treasury Shares Number          bs         coca   
1                  Ordinary Shares Number          bs         coca   
2                            Share Issued          bs         coca   
3                                Net Debt          bs         coca   
4                              Total Debt          bs         coca   
..                                    ...         ...          ...   
59                           Depreciation          cf        pepsi   
60                 Operating Gains Losses          cf        pepsi   
61   Pension And Employee Benefit Expense          cf        pepsi   
62          Gain Loss On Sale Of Business          cf        pepsi   
63  Net Income From Continuing Operations          cf        pepsi   

       2022-12-31     2021-12-31     2020-12-31     2019-12-31  
0    2712000000.0   2715000000.0   2738000000.0   2760000000.0  
1    4328000000.0   4325128924.0   4302128924.0   4280128924.0  
2    7040000000.0   7040128924.0   7040128924.0   7040128924.0  
3   29630000000.0  33077000000.0  35998000000.0  36283000000.0  
4   39149000000.0  42761000000.0  42793000000.0  42763000000.0  
..            ...            ...            ...            ...  
59   3280000000.0   3215000000.0            NaN            NaN  
60  -2902000000.0    123000000.0    408000000.0    519000000.0  
61    419000000.0    123000000.0    408000000.0    519000000.0  
62  -3321000000.0            NaN            NaN            NaN  
63   8978000000.0   7679000000.0   7175000000.0   7353000000.0  

[378 rows x 7 columns]

In [18]:
form10k_inone.to_excel('form10k_inone.xlsx')

In [19]:
import pandas as pd

companies = form10k_inone['Company Name'].unique()

new_rows = []

for company in companies:
    company_data = form10k_inone[form10k_inone['Company Name'] == company]

    total_assets = company_data.iloc[:, 3:].loc[company_data['Financial Indicators'] == 'Total Assets'].values
    total_debt = company_data.iloc[:, 3:].loc[company_data['Financial Indicators'] == 'Total Debt'].values
    net_assets = total_assets - total_debt
    
    new_row_data = [net_assets[0, col - 3] for col in range(3, len(form10k_inone.columns))]
    new_row_data = ['Net Assets', 'bs', company] + new_row_data

    # create new rows to accommodate the new born metrics
    new_row = dict(zip(form10k_inone.columns, new_row_data))

    new_rows.append(new_row)

# insert the new records
form10k_inone = pd.concat([form10k_inone, pd.DataFrame(new_rows)], ignore_index=True)

# delete useless columns, if any
form10k_inone = form10k_inone.dropna(axis=1, how='all')





In [20]:
import pandas as pd
import numpy as np

def avrg_balance(form10k_inone, financial_indicator):
    new_rows = []

    for _, company_data in form10k_inone.groupby('Company Name'):
        # get the data of the indicator so to calc average
        indicator_data = company_data.loc[company_data['Financial Indicators'] == financial_indicator, form10k_inone.columns[3:]]

        # calculate moving average
        avg_balances = [
            np.nanmean(indicator_data.iloc[:, col-2:col].values)
            for col in range(2, len(form10k_inone.columns))
        ]

        # create new row
        new_row_data = [financial_indicator + 'MA', 'bs', company_data['Company Name'].iloc[0]] + avg_balances

        # zip the row
        new_row = dict(zip(form10k_inone.columns, new_row_data))

        new_rows.append(new_row)

    # insert the new rows into the original df
    form10k_inone = pd.concat([form10k_inone, pd.DataFrame(new_rows)], ignore_index=True)

    # delete null columns, if any
    form10k_inone = form10k_inone.dropna(axis=1, how='all')

    return form10k_inone

# calc MA of Total Assets
form10k_inone = avrg_balance(form10k_inone, 'Total Assets')



/var/folders/nr/053gf3x97yg912g1cs827wrw0000gn/T/ipykernel_3001/2080370539.py:13: RuntimeWarning: Mean of empty slice
  np.nanmean(indicator_data.iloc[:, col-2:col].values)


In [21]:
#calc MA of Accounts Payable
form10k_inone = avrg_balance(form10k_inone, 'Accounts Payable')

/var/folders/nr/053gf3x97yg912g1cs827wrw0000gn/T/ipykernel_3001/2080370539.py:13: RuntimeWarning: Mean of empty slice
  np.nanmean(indicator_data.iloc[:, col-2:col].values)


In [22]:
#calc MA of Accounts Receivable
form10k_inone = avrg_balance(form10k_inone, 'Accounts Receivable')

/var/folders/nr/053gf3x97yg912g1cs827wrw0000gn/T/ipykernel_3001/2080370539.py:13: RuntimeWarning: Mean of empty slice
  np.nanmean(indicator_data.iloc[:, col-2:col].values)


In [23]:
#calc MA of Inventory
form10k_inone = avrg_balance(form10k_inone, 'Inventory')

/var/folders/nr/053gf3x97yg912g1cs827wrw0000gn/T/ipykernel_3001/2080370539.py:13: RuntimeWarning: Mean of empty slice
  np.nanmean(indicator_data.iloc[:, col-2:col].values)


In [24]:
# 1. Metrics 1 --making net income for profitability
corp = "coca"
nom = 'Net Income'
denom = 'Total Revenue'
nomsource = 'is'
denomsource = 'is'


def get_rate(corp, nom, denom, nomsource, denomsource):
    nom_data = form10k_inone[(form10k_inone['Data Source'].isin([nomsource])) & (form10k_inone['Company Name']== corp) & (form10k_inone['Financial Indicators'] == nom)]
    denom_data = form10k_inone[(form10k_inone['Data Source'].isin([denomsource])) & (form10k_inone['Company Name']== corp) & (form10k_inone['Financial Indicators'] == denom)]
    
    nom_values=nom_data.iloc[:,3:].values
    denom_values=denom_data.iloc[:,3:].values
    
    rate=nom_values/denom_values
    return rate

get_rate(corp,nom,denom,nomsource,denomsource)

array([[0.2218863361547763, 0.2527745440434614, 0.23465802386866177,
        0.23936027478130198]], dtype=object)

In [25]:
get_rate("pepsi",nom,denom,nomsource,denomsource)

array([[0.10313454949532364, 0.09585524825729169, 0.10117660433126811,
        0.10890248805110109]], dtype=object)

In [26]:
#2. Metrics 2 --gross margin rate also for profitability
get_rate("coca","Gross Profit","Total Revenue","is","is")

array([[0.5814342851827737, 0.6027163368257664, 0.5931120130853578,
        0.6077121236515859]], dtype=object)

In [27]:
get_rate("pepsi","Gross Profit","Total Revenue","is","is")

array([[0.5303268821187147, 0.5334952311447769, 0.5481583584380151,
        0.5513467637468173]], dtype=object)

In [28]:
#3. Metrics 3 --Free Cash Flow to Total Revenue
get_rate("coca","Free Cash Flow","Total Revenue","cf","is")


array([[0.22170030694819087, 0.29124304747121976, 0.26252498939843705,
        0.22586271668545055]], dtype=object)

In [29]:
get_rate("pepsi","Free Cash Flow","Total Revenue","cf","is")

array([[0.0648671173256783, 0.08796587563228225, 0.09056158699482748,
        0.08065692887241108]], dtype=object)

In [30]:
#3. Metrics 3--Cash Conversion Rate : select one between this and above: this use operating cashflow devided by net income to measure the corp's ability to generate cash from its operations
get_rate("coca","Operating Cash Flow","Net Income","cf","is")

array([[1.154684552504716, 1.2920888343055983, 1.2706854266167549,
        1.1738789237668161]], dtype=object)

In [31]:
get_rate("pepsi","Operating Cash Flow","Net Income","cf","is")
## the downside is both companies have very strong cashflow and its always over 1,kinda hard to explain, but this metric is more common

array([[1.2133557800224466, 1.5248096613284328, 1.4905898876404495,
        1.3192507519824994]], dtype=object)

In [32]:
#4. Metrics 4-- solvency:leverage ratio debt-to-equity ratio
get_rate("pepsi","Total Debt","Net Assets","bs","bs")

array([[0.7355787333383538, 0.775012970044002, 0.9053067585301837,
        0.6899459971169776]], dtype=object)

In [33]:
get_rate("coca","Total Debt","Net Assets","bs","bs")

array([[0.730201066885515, 0.828813986393503, 0.9615756241152282,
        0.9803980008253473]], dtype=object)

In [34]:
#4. Metrics 4--solvency: leverage ratio debt-to-assets --select one from the two
get_rate("pepsi","Total Debt","Total Assets","bs","bs")

array([[0.4238233156518815, 0.4366238349372679, 0.47515013237478204,
        0.4082651151539842]], dtype=object)

In [35]:
#4. Metrics 4--solvency: leverage ratio debt-to-assets
get_rate("coca","Total Debt","Total Assets","bs","bs")

array([[0.42203249140282223, 0.45319753269601715, 0.4902057368035191,
        0.49505099501047684]], dtype=object)

In [36]:
#5. Calculate DSO
get_rate("coca","Accounts ReceivableMA","Total Revenue","bs","is")*360

array([[29.295414380057668, 30.9941792782305, 38.79263342824257,
        38.360972468201574]], dtype=object)

In [37]:
#5. Calculate DSO
get_rate("pepsi","Accounts ReceivableMA","Total Revenue","bs","is")*360

array([[39.2598851745532, 38.6934091652616, 41.50343886773148,
        41.92790458748381]], dtype=object)

In [38]:
#6. Calculate ITO
get_rate("coca","InventoryMA","Cost Of Revenue","bs","is")*360

array([[76.47, 78.29654229341669, 89.04191170996799, 83.20952185512006]],
      dtype=object)

In [39]:
get_rate("pepsi","InventoryMA","Cost Of Revenue","bs","is")*360

array([[42.44923107255521, 41.35994605529332, 42.513444664591,
        39.8805256869773]], dtype=object)

In [40]:
#6. Calculate DPO
get_rate("coca","Accounts PayableMA","Cost Of Revenue","bs","is")*360

array([[303.68, 301.9808556358664, 300.9201220873967, 278.56351323619947]],
      dtype=object)

In [41]:
#6. Calculate DPO
get_rate("pepsi","Accounts PayableMA","Cost Of Revenue","bs","is")*360

array([[197.54041798107255, 197.84706675657452, 210.2066232663459,
        209.56989247311827]], dtype=object)

In [43]:
#7.  Calculate Assets Turnover Rate
get_rate("coca","Total Revenue","Total AssetsMA","is","bs")

array([[0.45964824147458544, 0.42559867877786955, 0.3801769952267715,
        0.43141431564811705]], dtype=object)

In [44]:
get_rate("pepsi","Total Revenue","Total AssetsMA","is","bs")

array([[0.9361739017359831, 0.857810518362611, 0.8208322398157059,
        0.8550422040307077]], dtype=object)

In [45]:
#8. Calculate the Current Ratio
get_rate("coca","Current Assets","Current Liabilities","bs","bs")

array([[1.1453559115798013, 1.130075187969925, 1.317717964522978,
        0.7567196826456086]], dtype=object)

In [46]:
get_rate("pepsi","Current Assets","Current Liabilities","bs","bs")

array([[0.8041441105096135, 0.8307780320366133, 0.9841263049803183,
        0.8623723180685205]], dtype=object)

In [47]:
#9. Calculate the interest coverage ratio---Solvency
get_rate("coca","EBIT","Interest Expense","is","is")

array([[14.249433106575964, 8.780212899185974, 7.784272790535838,
        12.40169133192389]], dtype=object)

In [48]:
get_rate("pepsi","EBIT","Interest Expense","is","is")

array([[12.400425985090521, 6.271604938271605, 9.039893617021276,
        9.204405286343613]], dtype=object)

In [ ]:
#for metrics such as EPS or Revenue, the dataframe already has it.
#the above order is a bit messy, we can adjust a bit the order in the end, conforming to our context